import { Game } from '../types/game';

// ─── Game Constants ──────────────────────────────────────────────────────────

export const GAMES: Game[] = [
  {
    id: 'ludo',
    name: 'Ludo',
    description: 'Classic Ludo board game with animated tokens',
    icon: 'ludo_icon',
    banner: 'ludo_banner',
    minPlayers: 2,
    maxPlayers: 4,
    estimatedDuration: '20-40 min',
    modes: ['classic', 'quick', 'private', 'practice'],
    isActive: true,
    isFeatured: true,
    category: 'board',
  },
  {
    id: 'chess',
    name: 'Chess',
    description: 'Strategic chess with time controls',
    icon: 'chess_icon',
    banner: 'chess_banner',
    minPlayers: 2,
    maxPlayers: 2,
    estimatedDuration: '10-60 min',
    modes: ['classic', 'quick', 'private', 'practice'],
    isActive: true,
    isFeatured: true,
    category: 'strategy',
  },
  {
    id: 'uno',
    name: 'Uno',
    description: 'The classic card game for 2-4 players',
    icon: 'uno_icon',
    banner: 'uno_banner',
    minPlayers: 2,
    maxPlayers: 4,
    estimatedDuration: '15-30 min',
    modes: ['classic', 'quick', 'private'],
    isActive: true,
    isFeatured: false,
    category: 'card',
  },
  {
    id: 'snakeLadder',
    name: 'Snake & Ladder',
    description: 'Luck-based classic board game',
    icon: 'snake_icon',
    banner: 'snake_banner',
    minPlayers: 2,
    maxPlayers: 4,
    estimatedDuration: '10-20 min',
    modes: ['classic', 'quick', 'private'],
    isActive: true,
    isFeatured: false,
    category: 'casual',
  },
  {
    id: 'chidiyaUdd',
    name: 'Chidiya Udd',
    description: 'Fast-paced reaction game — tap when the bird flies!',
    icon: 'chidiya_icon',
    banner: 'chidiya_banner',
    minPlayers: 2,
    maxPlayers: 6,
    estimatedDuration: '5-10 min',
    modes: ['classic', 'quick', 'private'],
    isActive: true,
    isFeatured: false,
    category: 'casual',
  },
  {
    id: 'esto',
    name: 'Esto',
    description: 'A unique multi-player strategy game',
    icon: 'esto_icon',
    banner: 'esto_banner',
    minPlayers: 2,
    maxPlayers: 4,
    estimatedDuration: '15-25 min',
    modes: ['classic', 'quick', 'private'],
    isActive: true,
    isFeatured: false,
    category: 'strategy',
  },
];

export const GAME_TURN_TIME_SECONDS = 30;
export const GAME_MAX_IDLE_SECONDS = 60;
